### ISSUE TITLE
Inspectable generated diff

### ISSUE THREAD

**Issue by saskenuba** [knickish/structdiff#26]
Hello! 

I have the use case of having a struct on memory, and I want to take the diff between it and the same struct after various transformations are applied and save only the changes to the database. After some code inspection, the intermediate result generated by `diff` method is not inspectable. Is this a use case the library wants to support? I haven't found any similar crate on the ecosystem.

**Comment by knickish** [comment]
Hello, does activating the `debug_diffs` (implements `Debug` for the intermediate type) solve your problem, or are you looking for something else?

**Comment by knickish** [comment]
@saskenuba Going to go ahead and close this, please let me know if this didn't solve your issue and I'll reopen
